version: "3.9"
services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik_letsencrypt:/letsencrypt

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: school
      DB_USER: school
      DB_PASSWORD: school
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "False"
      ALLOWED_HOSTS: "${FRONTEND_HOST},${BACKEND_HOST}"
      CORS_ALLOWED_ORIGINS: "https://${FRONTEND_HOST}"
      CSRF_TRUSTED_ORIGINS: "https://${FRONTEND_HOST}"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_HOST}`) || (Host(`${FRONTEND_HOST}`) && PathPrefix(`/api`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"

volumes:
  db_data:
  traefik_letsencrypt:
