# Generated by Django 5.2.5 on 2025-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=50),
        ),
    ]
