# Generated by Django 5.2.5 on 2025-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_adminuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
