# Generated by Django 5.2.5 on 2025-08-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adminuser_django_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
    ]
